# Generated by Django 3.1.5 on 2021-03-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Имя пользователя', 'verbose_name_plural': 'Имя пользователей'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
